import { z } from 'zod';

export const invoiceItemSchema = z.object({
  qualityId: z.number({ required_error: 'Quality is required' }),
  hsnNumber: z.string().max(8).optional().default('7113'),
  quantity: z.number().optional().default(0),
  carats: z.number({ required_error: 'Carats is required' }).positive('Carats must be positive'),
  pieces: z.number().min(0).optional().nullable().default(1),
  isPiecesUncounted: z.boolean().optional().default(false),
  rate: z.number({ required_error: 'Rate is required' }).min(0, 'Rate cannot be negative'),
  discountPct: z.number().min(0).max(100).default(0),
  stockPacketId: z.number().nullable().optional(),
  stockIdNumber: z.string().optional(),
  isManualStockId: z.boolean().optional().default(false),
  category: z.string().optional(),
  shape: z.string().optional(),
  color: z.string().optional(),
  clarity: z.string().optional(),
  cut: z.string().optional(),
  polish: z.string().optional(),
  symmetry: z.string().optional(),
  certificateType: z.string().optional(),
  certificateNumber: z.string().optional(),
  lengthMm: z.number().optional().nullable(),
  widthMm: z.number().optional().nullable(),
  depthMm: z.number().optional().nullable(),
  totalDepthPct: z.number().optional().nullable(),
  tablePct: z.number().optional().nullable(),
  imageLink: z.string().optional(),
  videoLink: z.string().optional(),
});

export const invoiceSchema = z.object({
  financialYearId: z.number({ required_error: 'Financial year is required' }),
  invoiceType: z.enum([
    'SALE_INVOICE',
    'SALE_RETURN',
    'SALE_DEBIT_NOTE',
    'PURCHASE_INVOICE',
    'PURCHASE_RETURN',
    'PURCHASE_DEBIT_NOTE',
  ]),
  referenceInvoiceId: z.number().nullable().optional(),
  referenceBillNumber: z.string().nullable().optional(),
  isManualBillNumber: z.boolean().default(false),
  billNumber: z.string().optional().or(z.literal('')),
  invoiceDate: z.string().min(1, 'Invoice date is required'),
  customerId: z.number({ required_error: 'Party / Client is required' }),
  brokerId: z.number().nullable().optional(),
  brokeragePct: z.number().min(0).max(100).default(0),
  creditDays: z.number().min(0).default(0),
  addPct: z.number().min(0).max(100).default(0),
  lessPct: z.number().min(0).max(100).default(0),
  totalCgst: z.number().min(0).default(0),
  totalSgst: z.number().min(0).default(0),
  totalIgst: z.number().min(0).default(0),
  narration: z.string().optional().or(z.literal('')),
  items: z.array(invoiceItemSchema).min(1, 'At least one item must be added'),
});

export type InvoiceFormData = z.infer<typeof invoiceSchema>;
export type InvoiceItemFormData = z.infer<typeof invoiceItemSchema>;
